config:
  host: devx-helloworld-springboot-9cnuc.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-9cnuc-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-9cnuc-docker-dev-local/devx-helloworld-springboot-9cnuc
    tag: 0.0.1-SNAPSHOT
